package com.moneymapping.backend

import jakarta.persistence.Entity        // marks this class as a JPA entity mapped to a database table
import jakarta.persistence.GeneratedValue // tells JPA to auto-generate the ID value
import jakarta.persistence.GenerationType // specifies IDENTITY strategy — database handles auto-increment
import jakarta.persistence.Id             // marks the primary key field
import jakarta.persistence.Table          // specifies the exact table name in the database

@Entity
@Table(name = "credits") // the database table will be called "credits"
data class Credit(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID — same pattern as SpendingLimit
    val id: Long = 0,           // unique ID for this credit record — generated by the database

    val userId: String,         // the ID of the user who received this credit — links credit to the right person

    val amount: Double,         // the credit amount e.g. 20.0 — this will be subtracted from the spent total

    val comment: String,        // a short note the user wrote e.g. "Ahmad paid me back $50 for dinner"

    val date: String,            // the date this credit was added — stored as "yyyy-MM-dd" string, same as expenses

    val currency: String = ""   // the currency this credit was received in e.g. "RUB"

)