package com.moneymapping.backend

import com.sirolf2009.modulith.account.VerifyToken           // verifies the JWT access token — same pattern used in all other controllers
import com.sirolf2009.modulith.cqrs.execute                  // executes commands from the auth library
import org.springframework.http.HttpStatus                    // HTTP status codes like 200, 401
import org.springframework.http.ResponseEntity               // allows returning custom HTTP status codes with a body
import org.springframework.web.bind.annotation.GetMapping    // marks a function as a GET endpoint
import org.springframework.web.bind.annotation.PostMapping   // marks a function as a POST endpoint
import org.springframework.web.bind.annotation.RequestBody   // reads the request body as JSON
import org.springframework.web.bind.annotation.RequestHeader // reads a specific request header
import org.springframework.web.bind.annotation.RequestMapping // sets the base path for all endpoints in this controller
import org.springframework.web.bind.annotation.RestController // marks this class as a REST controller that returns JSON

@RestController
@RequestMapping("/credits") // all endpoints in this controller start with /credits
class CreditController(
    private val creditRepository: CreditRepository // injected automatically by Spring — used to save and fetch credits
) {

    // extracts and verifies the Bearer token — returns the userId or null if invalid
    // same pattern used in SpendingLimitController and all other controllers
    private fun getUserId(authHeader: String?): String? {
        val token = authHeader?.removePrefix("Bearer ")?.trim() ?: return null // strips the "Bearer " prefix from the header
        return try {
            execute(VerifyToken(token))?.userId // verifies the token and returns the userId
        } catch (e: Exception) {
            null // returns null if the token is invalid or expired
        }
    }

    // handles POST /credits — saves a new credit entry for the logged-in user
    @PostMapping
    fun addCredit(
        @RequestHeader("Authorization") authHeader: String, // reads the Authorization header from the request
        @RequestBody request: AddCreditRequest              // reads the request body as JSON
    ): ResponseEntity<Any> {
        val userId = getUserId(authHeader)
            ?: return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid or expired token") // rejects if token is bad

        val credit = Credit(
            userId = userId,            // links the credit to the logged-in user
            amount = request.amount,    // the credit amount e.g. 20.0
            comment = request.comment,  // the user's note e.g. "Ahmad paid me back $50"
            date = request.date,        // the date as "yyyy-MM-dd"
            currency = request.currency // the currency this credit was received in e.g. "RUB"
        )

        return ResponseEntity.ok(creditRepository.save(credit)) // saves to the database and returns the saved credit
    }

    // handles GET /credits — returns all credits for the logged-in user
    @GetMapping
    fun getCredits(
        @RequestHeader("Authorization") authHeader: String // reads the Authorization header from the request
    ): ResponseEntity<Any> {
        val userId = getUserId(authHeader)
            ?: return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid or expired token") // rejects if token is bad

        val credits = creditRepository.findByUserId(userId) // fetches all credits for this user from the database

        return ResponseEntity.ok(credits) // returns the list of credits as JSON
    }
}

// the request body sent when adding a new credit
data class AddCreditRequest(
    val amount: Double,  // the credit amount e.g. 20.0
    val comment: String, // a short note e.g. "Ahmad paid me back $50 for dinner"
    val date: String,    // the date as "yyyy-MM-dd"
    val currency: String = "" // the currency this credit was received in e.g. "RUB"
)

// the response returned after saving or fetching a credit
data class CreditResponse(
    val id: Long,        // the credit's unique ID generated by the database
    val userId: String,  // the user this credit belongs to
    val amount: Double,  // the credit amount
    val comment: String, // the user's note
    val date: String,    // the date as "yyyy-MM-dd"
    val currency: String = "" // the currency this credit was received in — defaults to empty if not set
)