package com.moneymapping.backend

import jakarta.persistence.Entity         // marks this as a database entity
import jakarta.persistence.GeneratedValue // auto-generates the ID
import jakarta.persistence.GenerationType // specifies the ID generation strategy
import jakarta.persistence.Id             // marks the primary key
import jakarta.persistence.Table          // specifies the table name

@Entity
@Table(name = "expense_items") // the table will be called "expense_items"
data class ExpenseItem(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID
    val id: Long = 0,           // unique ID for this item — auto generated by the database

    val expenseId: String,      // the ID of the expense this item belongs to

    val name: String,           // item name e.g. "Pizza"

    val unitPrice: Double,      // price per unit

    val quantity: Double,       // quantity — Double to support weight-based items like 0.265 kg

    val totalPrice: Double      // unit price × quantity
)