package com.moneymapping.backend

import jakarta.persistence.Entity        // marks this class as a database entity
import jakarta.persistence.GeneratedValue // auto-generates the ID
import jakarta.persistence.GenerationType // specifies the ID generation strategy
import jakarta.persistence.Id             // marks the primary key
import jakarta.persistence.Table          // specifies the table name

@Entity
@Table(name = "group_members") // the table will be called "group_members" in the database
data class GroupMember(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID
    val id: Long = 0,           // unique ID for this membership — auto generated by the database

    val groupId: Long,          // the ID of the group this membership belongs to

    val userId: String?,        // the user ID — null if this member is a guest (no account)

    val guestName: String?,     // the guest's name — null if this is a real registered user

    val role: String = "MEMBER" // the member's role — "ADMIN" or "MEMBER"
)