package com.moneymapping.backend

import jakarta.persistence.Entity        // marks this class as a database entity
import jakarta.persistence.GeneratedValue // auto-generates the ID
import jakarta.persistence.GenerationType // specifies the ID generation strategy
import jakarta.persistence.Id             // marks the primary key
import jakarta.persistence.Table          // specifies the table name

@Entity
@Table(name = "groups") // the table will be called "groups" in the database
data class Group(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID
    val id: Long = 0,           // unique ID for this group — auto generated by the database

    val name: String,           // the display name of the group e.g. "Family" or "Trip to Paris"

    val type: String,           // the group type — "FRIEND", "FAMILY", or "ONE_TIME"

    val createdBy: String,      // the user ID of whoever created the group

    val isLocked: Boolean = false // true when a ONE_TIME group is settled and becomes read-only
)