package com.moneymapping.backend

import jakarta.persistence.Entity         // marks this as a database entity
import jakarta.persistence.GeneratedValue // auto-generates the ID
import jakarta.persistence.GenerationType // specifies the ID generation strategy
import jakarta.persistence.Id             // marks the primary key
import jakarta.persistence.Table          // specifies the table name

@Entity
@Table(name = "item_assignments") // the table will be called "item_assignments"
data class ItemAssignment(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID
    val id: Long = 0,           // unique ID for this assignment — auto generated by the database

    val expenseItemId: Long,    // the ID of the expense item this assignment belongs to

    val personName: String,     // the name of the person assigned — either a username or guest name

    val quantity: Double,       // how many units of the item this person is taking

    val shareAmount: Double     // how much this person owes — calculated as (quantity / totalQuantity) × itemTotalPrice
)