package com.moneymapping.backend

import jakarta.persistence.Entity         // marks this as a database entity
import jakarta.persistence.GeneratedValue // auto-generates the ID
import jakarta.persistence.GenerationType // specifies the ID generation strategy
import jakarta.persistence.Id             // marks the primary key
import jakarta.persistence.Table          // specifies the table name

@Entity
@Table(name = "paid_debts") // the table will be called "paid_debts"
data class PaidDebt(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID
    val id: Long = 0,           // unique ID for this record — auto generated by the database

    val groupId: Long,          // the group this settled debt belongs to

    val fromUserId: String,     // the person who was owing money — stored as username to match balance calculation

    val toUserId: String,       // the person who was owed money — stored as username to match balance calculation

    val amount: Double,         // the exact amount that was settled at the time of clicking "Paid"

    val settledDate: String     // the date this debt was marked as paid — stored as "yyyy-MM-dd"
)