package com.moneymapping.backend

import jakarta.persistence.Entity         // marks this as a database entity
import jakarta.persistence.EnumType       // specifies that the enum is stored as a string
import jakarta.persistence.Enumerated     // tells JPA how to store the enum
import jakarta.persistence.GeneratedValue // auto-generates the ID
import jakarta.persistence.GenerationType // specifies the ID generation strategy
import jakarta.persistence.Id             // marks the primary key
import jakarta.persistence.Table          // specifies the table name

@Entity
@Table(name = "payment_plans") // the table will be called "payment_plans"
data class PaymentPlan(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID
    val id: Long = 0,               // unique ID for this payment plan — auto generated by the database

    val groupId: Long,              // the group this payment plan belongs to

    val fromUserId: String,         // the user ID of the person who owes money

    val toUserId: String,           // the user ID of the person who is owed money

    val totalAmount: Double,        // the total debt amount being paid off

    val startDate: String,          // the date the plan starts — stored as "yyyy-MM-dd"

    val endDate: String,            // the date the plan ends — stored as "yyyy-MM-dd"

    @Enumerated(EnumType.STRING)    // stores the enum as a string e.g. "WEEKLY" instead of a number
    val frequency: PaymentFrequency, // how often installments are due

    val installmentAmount: Double,  // the amount due per installment — auto calculated when plan is created

    val status: String = "ACTIVE"   // ACTIVE while ongoing, COMPLETED when all installments are paid
)

// the possible frequencies for a payment plan
enum class PaymentFrequency {
    DAILY,   // one installment per day
    WEEKLY,  // one installment per week
    MONTHLY  // one installment per month
}