package com.moneymapping.backend

import jakarta.persistence.Entity         // marks this as a database entity
import jakarta.persistence.GeneratedValue // auto-generates the ID
import jakarta.persistence.GenerationType // specifies the ID generation strategy
import jakarta.persistence.Id             // marks the primary key
import jakarta.persistence.Table          // specifies the table name

@Entity
@Table(name = "payment_plan_installments") // the table will be called "payment_plan_installments"
data class PaymentPlanInstallment(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID
    val id: Long = 0,               // unique ID for this installment — auto generated by the database

    val paymentPlanId: Long,        // the ID of the payment plan this installment belongs to

    val dueDate: String,            // the date this installment is due — stored as "yyyy-MM-dd"

    val amount: Double,             // the amount due for this installment

    val isPaid: Boolean = false,    // false by default — true once the person marks it as paid

    val paidDate: String? = null    // the date it was marked as paid — null if not yet paid
)