package com.moneymapping.backend

import jakarta.persistence.Entity        // marks this class as a JPA entity mapped to a database table
import jakarta.persistence.GeneratedValue // tells JPA to auto-generate the ID value
import jakarta.persistence.GenerationType // specifies IDENTITY strategy — database handles auto-increment
import jakarta.persistence.Id             // marks the primary key field
import jakarta.persistence.Table          // specifies the exact table name in the database

@Entity
@Table(name = "recurring_expenses")      // the database table will be called "recurring_expenses"
data class RecurringExpense(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID — database handles this
    val id: Long = 0,                    // unique ID for this recurring expense — generated by the database

    val userId: String,                  // the ID of the user this recurring expense belongs to

    val name: String,                    // the name of the recurring expense e.g. "Netflix" or "Gym membership"

    val amount: Double,                  // how much this expense costs per period e.g. 9.99

    val currency: String,                // the currency this expense is in e.g. "USD"

    val category: String,                // the category e.g. "Entertainment" or "Housing"

    val frequency: String,               // how often this expense recurs — "DAILY", "WEEKLY", or "MONTHLY"

    val dayOfMonth: Int? = null,         // which day of the month it is due — only used when frequency is MONTHLY e.g. 15

    val dayOfWeek: Int? = null,          // which day of the week it is due — only used when frequency is WEEKLY e.g. 1=Monday 7=Sunday

    val lastExecutedDate: String? = null // the last date this recurring expense auto-created a personal expense — stored as "yyyy-MM-dd" — null means never executed
)