package com.moneymapping.backend

import com.sirolf2009.modulith.account.VerifyToken           // verifies the JWT access token — same pattern used in all other controllers
import com.sirolf2009.modulith.cqrs.execute                  // executes commands from the auth library
import org.springframework.http.HttpStatus                    // HTTP status codes like 200, 401
import org.springframework.http.ResponseEntity               // wraps the response with an HTTP status code
import org.springframework.web.bind.annotation.DeleteMapping // maps DELETE requests to this function
import org.springframework.web.bind.annotation.GetMapping    // maps GET requests to this function
import org.springframework.web.bind.annotation.PathVariable  // extracts a value from the URL path
import org.springframework.web.bind.annotation.PostMapping   // maps POST requests to this function
import org.springframework.web.bind.annotation.PutMapping    // maps PUT requests to this function
import org.springframework.web.bind.annotation.RequestBody   // reads the request body as a Kotlin object
import org.springframework.web.bind.annotation.RequestHeader // reads a value from the request header
import org.springframework.web.bind.annotation.RequestMapping // sets the base URL path for all endpoints in this controller
import org.springframework.web.bind.annotation.RestController // marks this class as a REST controller — handles HTTP requests and returns JSON

// ─── Request / Response models ────────────────────────────────────────────────

// the request body sent when creating a new recurring expense
data class CreateRecurringExpenseRequest(
    val name: String,               // the name e.g. "Netflix"
    val amount: Double,             // how much it costs per period e.g. 9.99
    val currency: String,           // the currency e.g. "USD"
    val category: String,           // the category e.g. "Entertainment"
    val frequency: String,          // how often it recurs — "DAILY", "WEEKLY", or "MONTHLY"
    val dayOfMonth: Int? = null,    // which day of the month it is due — only for MONTHLY
    val dayOfWeek: Int? = null      // which day of the week it is due — only for WEEKLY e.g. 1=Monday 7=Sunday
)

// the request body sent when editing an existing recurring expense
data class UpdateRecurringExpenseRequest(
    val name: String,               // updated name
    val amount: Double,             // updated amount
    val currency: String,           // updated currency
    val category: String,           // updated category
    val frequency: String,          // updated frequency — "DAILY", "WEEKLY", or "MONTHLY"
    val dayOfMonth: Int? = null,    // updated day of month — only for MONTHLY
    val dayOfWeek: Int? = null      // updated day of week — only for WEEKLY
)

// the response sent back to the Android app after creating, updating or fetching a recurring expense
data class RecurringExpenseResponse(
    val id: Long,                       // the unique ID generated by the database
    val userId: String,                 // the user this recurring expense belongs to
    val name: String,                   // the name e.g. "Netflix"
    val amount: Double,                 // the amount per period
    val currency: String,               // the currency
    val category: String,               // the category
    val frequency: String,              // "DAILY", "WEEKLY", or "MONTHLY"
    val dayOfMonth: Int? = null,        // the day of month — null if not MONTHLY
    val dayOfWeek: Int? = null,         // the day of week — null if not WEEKLY
    val lastExecutedDate: String? = null // the last date a personal expense was auto-created for this — null if never
)

// ─── Controller ───────────────────────────────────────────────────────────────

@RestController
@RequestMapping("/recurring-expenses")  // all endpoints in this controller are under /recurring-expenses
class RecurringExpenseController(
    private val repository: RecurringExpenseRepository // injected automatically by Spring
) {

    // extracts and verifies the Bearer token — returns the userId or null if invalid
    private fun getUserId(authHeader: String?): String? {
        val token = authHeader?.removePrefix("Bearer ")?.trim() ?: return null // strips the "Bearer " prefix
        return try {
            execute(VerifyToken(token))?.userId                                 // verifies token and returns userId
        } catch (e: Exception) {
            null                                                                // returns null if token is invalid
        }
    }

    // POST /recurring-expenses — creates a new recurring expense for the logged-in user
    @PostMapping
    fun create(
        @RequestHeader("Authorization") authHeader: String,
        @RequestBody request: CreateRecurringExpenseRequest
    ): ResponseEntity<Any> {
        val userId = getUserId(authHeader)
            ?: return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid or expired token")

        val saved = repository.save(
            RecurringExpense(
                userId = userId,
                name = request.name,
                amount = request.amount,
                currency = request.currency,
                category = request.category,
                frequency = request.frequency,
                dayOfMonth = request.dayOfMonth,                     // null if not MONTHLY
                dayOfWeek = request.dayOfWeek                        // null if not WEEKLY
            )
        )
        return ResponseEntity.ok(saved.toResponse())
    }

    // GET /recurring-expenses — fetches all recurring expenses for the logged-in user
    @GetMapping
    fun getAll(
        @RequestHeader("Authorization") authHeader: String
    ): ResponseEntity<Any> {
        val userId = getUserId(authHeader)
            ?: return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid or expired token")

        val items = repository.findByUserId(userId)                   // fetches only this user's recurring expenses
        return ResponseEntity.ok(items.map { it.toResponse() })
    }

    // PUT /recurring-expenses/{id} — updates an existing recurring expense
    @PutMapping("/{id}")
    fun update(
        @RequestHeader("Authorization") authHeader: String,
        @PathVariable id: Long,                                       // the ID of the recurring expense to update
        @RequestBody request: UpdateRecurringExpenseRequest
    ): ResponseEntity<Any> {
        val userId = getUserId(authHeader)
            ?: return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid or expired token")

        val existing = repository.findById(id).orElse(null)
            ?: return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Not found") // returns 404 if it does not exist

        if (existing.userId != userId)
            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("Forbidden")   // returns 403 if it belongs to someone else

        val updated = repository.save(                               // saves the updated record — JPA updates because the ID already exists
            existing.copy(
                name = request.name,
                amount = request.amount,
                currency = request.currency,
                category = request.category,
                frequency = request.frequency,
                dayOfMonth = request.dayOfMonth,
                dayOfWeek = request.dayOfWeek
            )
        )
        return ResponseEntity.ok(updated.toResponse())
    }

    // DELETE /recurring-expenses/{id} — deletes a single recurring expense by its ID
    @DeleteMapping("/{id}")
    fun delete(
        @RequestHeader("Authorization") authHeader: String,
        @PathVariable id: Long                                        // the ID of the recurring expense to delete
    ): ResponseEntity<Any> {
        val userId = getUserId(authHeader)
            ?: return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid or expired token")

        val item = repository.findById(id).orElse(null)
            ?: return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Not found")

        if (item.userId != userId)
            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("Forbidden")

        repository.deleteById(id)
        return ResponseEntity.ok("Deleted")
    }

    // converts a RecurringExpense entity to a RecurringExpenseResponse — keeps controller responses clean
    private fun RecurringExpense.toResponse() = RecurringExpenseResponse(
        id = id,
        userId = userId,
        name = name,
        amount = amount,
        currency = currency,
        category = category,
        frequency = frequency,
        dayOfMonth = dayOfMonth,
        dayOfWeek = dayOfWeek,
        lastExecutedDate = lastExecutedDate
    )
}