package com.moneymapping.backend

import jakarta.persistence.Entity        // marks this class as a database entity
import jakarta.persistence.GeneratedValue // auto-generates the ID
import jakarta.persistence.GenerationType // specifies the ID generation strategy
import jakarta.persistence.Id             // marks the primary key
import jakarta.persistence.Table          // specifies the table name

@Entity
@Table(name = "spending_limits") // the table will be called "spending_limits" in the database
data class SpendingLimit(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto-increments the ID
    val id: Long = 0,           // unique ID for this limit — auto generated by the database

    val groupId: Long? = null,  // the group this limit belongs to — null if it's a personal limit

    val userId: String? = null, // the user this limit belongs to — null if it's a group-wide limit

    val amount: Double,         // the limit amount e.g. 500.0

    val period: String          // the period — "DAILY", "WEEKLY", or "MONTHLY"
)