spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/MoneyMapping
spring.datasource.username=tareg
spring.datasource.password=tareg98
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tareg123456789tareg@gmail.com
spring.mail.password=qzrh yyec sxgy omek
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
anthropic.api.key=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