spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/MoneyMapping
spring.datasource.username=tareg
spring.datasource.password=tareg98
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true